stages:
  - build
  - deploy

default:
  image: python:3.10.0-buster

build_telemq_broker:
  image: rust:1.56
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release

copy_to_linode_storage:
  before_script:
    - scripts/ci/configure_cli.sh
  stage: deploy
  script:
    - echo "Mock for copying to the linode storage"

start_test_instance:
  stage: deploy
  needs: ['copy_to_linode_storage']
  script:
    - echo "Mock for starting a test instance with a new build"
