broker_id = "broker-1"
cluster_id = "cluster-1"
account_id = "account-1"
max_connections = 100000
# tcp_port = 1884
# tls_port = 1886
log_level = "error"
# log_dest="file:./logfile"
anonymous_allowed = true
keep_alive = 60
activity_check_interval = 60
# auth_file = "./auth.toml"
# auth_endpoint = "http://localhost:8010/devices/login"
# websockets_allowed = true
# ws_port = 1880
# admin_api_port = 8080
# ip_whitelist = ['127.0.0.1/32']
# sys_topics_update_interval = 20
# session_store_url = "http://localhost:8086"
# cert_file = "./local-cert/server.crt"
# key_file = "./local-cert/server.key"
