[package]
name = "admin_proto"
version = "0.1.0"
edition = "2021"
description = "Admin API protocol types"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
